#!/bin/bash

#
# check for existing ssh key
#
ls -al ~/.ssh

#
# generate ssh key
#
ssh-keygen -t rsa -b 4096 -C "nmiller217@gmail.com"

#
# start ssh-agent service
#
eval "$(ssh-agent -s)"

#
# add key to ssh-agent
#
ssh-add ~/.ssh/id_rsa

#
# install xclip
# 
sudo apt-get install xclip

#
# copy public SSH key to clipboard
#
xclip -sel clip < ~/.ssh/id_rsa.pub
